/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String default_company_logo = "assets/images/default_company_logo.png";
  static const String default_user_pic = "assets/images/default_user_pic.jpg";
  static const String doc_file = "assets/icons/doc_file.svg";
  static const String Documents = "assets/icons/Documents.svg";
  static const String drop_box = "assets/icons/drop_box.svg";
  static const String excel_file = "assets/icons/excel_file.svg";
  static const String Figma_file = "assets/icons/Figma_file.svg";
  static const String folder = "assets/icons/folder.svg";
  static const String google_drive = "assets/icons/google_drive.svg";
  static const String logo = "assets/icons/logo.svg";
  static const String logo_2 = "assets/images/logo_2.png";
  static const String media = "assets/icons/media.svg";
  static const String media_file = "assets/icons/media_file.svg";
  static const String menu_dashboard = "assets/icons/menu_dashboard.svg";
  static const String menu_doc = "assets/icons/menu_doc.svg";
  static const String menu_notification = "assets/icons/menu_notification.svg";
  static const String menu_profile = "assets/icons/menu_profile.svg";
  static const String menu_setting = "assets/icons/menu_setting.svg";
  static const String menu_store = "assets/icons/menu_store.svg";
  static const String menu_task = "assets/icons/menu_task.svg";
  static const String menu_tran = "assets/icons/menu_tran.svg";
  static const String one_drive = "assets/icons/one_drive.svg";
  static const String pdf_file = "assets/icons/pdf_file.svg";
  static const String profile_pic = "assets/images/profile_pic.png";
  static const String Search = "assets/icons/Search.svg";
  static const String sound_file = "assets/icons/sound_file.svg";
  static const String unknown = "assets/icons/unknown.svg";
  static const String xd_file = "assets/icons/xd_file.svg";
}
